services:
  db:
    image: mysql:8
    container_name: cartrllo-db
    environment:
      MYSQL_DATABASE: CarTrello
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Dani24117318
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cartrllo-net

  app:
    build: .
    container_name: cartrllo-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CarTrello
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dani24117318
    networks:
      - cartrllo-net

volumes:
  db_data:

networks:
  cartrllo-net:
